INSERT INTO ADRESSE (LIGNE1, LIGNE2, CODE_POSTAL, VILLE) VALUES ('16 rue des lilas d''Espagne', 'Appartement 12', 92400, 'Courbevoie');
INSERT INTO CLIENT (PRENOM, NOM, ADRESSE_ID) VALUES ('Eric', 'Siber', 1);
INSERT INTO COMMANDE (NOMBRE_PRODUITS, MONTANT, DATE_COMMANDE, CLIENT_ID) VALUES (2, 150, CURRENT_DATE, 1);
INSERT INTO users VALUES ('eric', 'passwordDb', true);
INSERT INTO authorities VALUES ('eric', 'ROLE_USER');
INSERT INTO authorities VALUES ('eric', 'ROLE_ADMIN');